apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: authentication-ingress
  namespace: authentication
spec:
  rules:
  - http:
      paths:
      - path: /auth
        backend:
          serviceName: keycloak
          servicePort: 8080