version: '3'

volumes:
    db_data:
        driver: local

services: 
    keycloak:
        build: ./.docker/keycloak
        container_name: keycloak
        restart: always
        tty: true
        ports: 
            - 7000:8080
        environment: 
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_ADDR: postgres
            DB_VENDOR: POSTGRES
            DB_DATABASE: keycloak
            DB_PORT: 5432
            DB_USER: keycloak
            DB_PASSWORD: keycloak
            KK_TO_RMQ_URL: host.docker.internal
            KK_TO_RMQ_PORT: 7300
            KK_TO_RMQ_VHOST: /
            KK_TO_RMQ_EXCHANGE: keycloak
            KK_TO_RMQ_USERNAME: guest
            KK_TO_RMQ_PASSWORD: guest
        depends_on: 
            - postgres
        networks:
            - internal-network
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    postgres:
        build: ./.docker/postgres
        container_name: postgres
        restart: always
        tty: true
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak
            POSTGRES_DB: keycloak
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes: 
            - db_data:/var/lib/postgresql/data
        networks:
            - internal-network

networks: 
    internal-network:
        driver: bridge