FROM quay.io/keycloak/keycloak:15.0.2

# COPY ./scripts/disable-theme-cache.cli /opt/jboss/startup-scripts/disable-theme-cache.cli

COPY ./keycloak-to-rabbit-1.0.jar /opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-1.0.jar